site_name: PyNSPD
site_url: https://yazmolod.github.io/pynspd
repo_url: https://github.com/yazmolod/pynspd

theme:
  name: material
  language: ru

  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - scheme: default
      primary: "light blue"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: "light blue"
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins: 
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_bases: false
            show_root_heading: true
            filters:
              - "!^_"


nav:
  - О проекте: README.md
  - Руководство пользователя: userguide.md
  - Расширенное руководство:
    - Какой клиент выбрать?: advanced/sync_vs_async.md
    - Настройка кэширования: advanced/caching.md
    - Типизация ответов: advanced/typing.md
    - Работа из консоли (CLI): advanced/cli.md
  - API Reference: 
      - pynspd.Nspd: api/client.md
      - pynspd.AsyncNspd: api/async_client.md
      - pynspd.NspdFeature: api/feature.md
      - pynspd.schemas.options.NspdProperties: api/properties.md
      - pynspd.schemas.options.NspdOptions: api/options.md
      - pynspd.types: api/types.md
      - pynspd.errors: api/errors.md
  - Как поддержать проект: contributing.md