# autogenerated
from datetime import datetime
from typing import Optional, Union

from pynspd.schemas.base_feature import BaseFeature
from pynspd.schemas.geometries import (
    LineString,
    MultiLineString,
    MultiPoint,
    MultiPolygon,
    Point,
    Polygon,
)
from pynspd.schemas.layer_configs import LayerNode
from pynspd.schemas.properties import NspdProperties, OptionProperties


class Options36368(OptionProperties):
    title_key = "cad_num"
    land_record_type: Optional[str] = None
    """Вид объекта недвижимости"""
    land_record_subtype: Optional[str] = None
    """Вид земельного участка"""
    land_record_reg_date: Optional[datetime] = None
    """Дата присвоения"""
    cad_num: Optional[str] = None
    """Кадастровый номер"""
    quarter_cad_number: Optional[str] = None
    """Кадастровый квартал"""
    readable_address: Optional[str] = None
    """Адрес"""
    specified_area: Optional[float] = None
    """Площадь уточненная (кв. м)"""
    declared_area: Optional[float] = None
    """Площадь декларированная (кв. м)"""
    area: Optional[float] = None
    """Площадь (кв. м)"""
    status: Optional[str] = None
    """Статус"""
    land_record_category_type: Optional[str] = None
    """Категория земель"""
    permitted_use_established_by_document: Optional[str] = None
    """Вид разрешенного использования"""
    ownership_type: Optional[str] = None
    """Форма собственности"""
    cost_value: Optional[float] = None
    """Кадастровая стоимость (руб.)"""
    cost_index: Optional[float] = None
    """Удельный показатель кадастровой стоимости (руб./кв. м)"""


class Options36369(OptionProperties):
    title_key = "cad_num"
    build_record_type_value: Optional[str] = None
    """Вид объекта недвижимости"""
    build_record_registration_date: Optional[datetime] = None
    """Дата присвоения"""
    cad_num: Optional[str] = None
    """Кадастровый номер"""
    quarter_cad_number: Optional[str] = None
    """Кадастровый квартал"""
    readable_address: Optional[str] = None
    """Адрес"""
    building_name: Optional[str] = None
    """Наименование"""
    purpose: Optional[str] = None
    """Назначение"""
    build_record_area: Optional[float] = None
    """Площадь общая (кв. м)"""
    status: Optional[str] = None
    """Статус"""
    ownership_type: Optional[str] = None
    """Форма собственности"""
    cost_value: Optional[float] = None
    """Кадастровая стоимость (руб.)"""
    cost_index: Optional[float] = None
    """Удельный показатель кадастровой стоимости (руб./ кв. м)"""
    floors: Optional[str] = None
    """Количество этажей (в том числе подземных)"""
    underground_floors: Optional[str] = None
    """Количество подземных этажей"""
    materials: Optional[str] = None
    """Материал стен"""
    year_built: Optional[str] = None
    """Завершение строительства (г.)"""
    year_commisioning: Optional[str] = None
    """Ввод в эксплуатацию (г.)"""
    cultural_heritage_val: Optional[str] = None
    """Сведения о включении объекта недвижимости в единый государственный реестр объектов культурного наследия (памятников истории и культуры) народов Российской Федерации"""
    united_cad_number: Optional[str] = None
    """Кадастровый номер единого недвижимого комплекса, в состав которого входит здание"""
    facility_cad_number: Optional[str] = None
    """Кадастровый номер предприятия как имущественного комплекса, в состав которого входит здание (имущественное право на здание)"""


class Options36381(OptionProperties):
    title_key = "cad_num"
    obj_kind_value: Optional[str] = None
    """Тип"""
    name: Optional[str] = None
    """Наименование"""
    cad_num: Optional[str] = None
    """Учетный номер"""
    cad_num_ko: Optional[str] = None
    """Кадастровый округ"""
    cad_num_kr: Optional[str] = None
    """Кадастровый район"""
    cnt_land: Optional[float] = None
    """Количество земельных участков"""
    cnt_land_geom: Optional[float] = None
    """с границами"""
    cnt_land_not_geom: Optional[float] = None
    """без границ"""
    cnt_oks: Optional[float] = None
    """Количество объектов капитального строительства"""
    cnt_oks_geom: Optional[float] = None
    """с границами"""
    cnt_oks_not_geom: Optional[float] = None
    """без границ"""
    cnt_enk: Optional[float] = None
    """Количество единых недвижимых комплексов"""
    cnt_pik: Optional[float] = None
    """Количество предприятий как имущественных комплексов"""


class Options36382(OptionProperties):
    title_key = "cad_num"
    obj_kind_value: Optional[str] = None
    """Тип"""
    name: Optional[str] = None
    """Наименование"""
    cad_num: Optional[str] = None
    """Учетный номер"""
    cad_num_ko: Optional[str] = None
    """Кадастровый округ"""
    cnt_kk: Optional[float] = None
    """Количество кадастровых кварталов"""
    cnt_land: Optional[float] = None
    """Количество земельных участков"""
    cnt_land_geom: Optional[float] = None
    """с границами"""
    cnt_land_not_geom: Optional[float] = None
    """без границ"""
    cnt_oks: Optional[float] = None
    """Количество объектов капитального строительства"""
    cnt_oks_geom: Optional[float] = None
    """с границами"""
    cnt_oks_not_geom: Optional[float] = None
    """без границ"""
    cnt_enk: Optional[float] = None
    """Количество единых недвижимых комплексов"""
    cnt_pik: Optional[float] = None
    """Количество предприятий как имущественных комплексов"""


class Options36383(OptionProperties):
    title_key = "cad_number"
    object_type_value: Optional[str] = None
    """Вид объекта недвижимости"""
    registration_date: Optional[datetime] = None
    """Дата присвоения"""
    cad_number: Optional[str] = None
    """Кадастровый номер"""
    quarter_cad_number: Optional[str] = None
    """Кадастровый квартал"""
    address_readable_address: Optional[str] = None
    """Адрес"""
    params_name: Optional[str] = None
    """Наименование"""
    params_purpose: Optional[str] = None
    """Назначение"""
    params_height: Optional[float] = None
    """высота (м.)"""
    params_depth: Optional[float] = None
    """глубина (м.)"""
    params_occurence_depth: Optional[float] = None
    """глубина залегания (м.)"""
    params_extension: Optional[float] = None
    """протяженность (м.)"""
    params_volume: Optional[float] = None
    """объем (куб. м)"""
    params_built_up_area: Optional[float] = None
    """Площадь застройки (кв. м)"""
    params_area: Optional[float] = None
    """Площадь (кв. м)"""
    object_previously_posted: Optional[str] = None
    """Статус"""
    ownership_type: Optional[str] = None
    """Форма собственности"""
    cost_value: Optional[float] = None
    """Кадастровая стоимость (руб.)"""
    cost_index: Optional[float] = None
    """Удельный показатель кадастровой стоимости (руб./кв. м)"""
    params_floors: Optional[str] = None
    """Количество этажей (в том числе подземных)"""
    params_underground_floors: Optional[str] = None
    """Количество подземных этажей"""
    params_year_built: Optional[str] = None
    """Завершение строительства"""
    params_year_commisioning: Optional[str] = None
    """Ввод в эксплуатацию"""
    cultural_heritage_object: Optional[str] = None
    """Сведения о включении объекта недвижимости в единый государственный реестр объектов культурного наследия (памятников истории и культуры) народов Российской Федерации"""
    united_cad_number: Optional[str] = None
    """Кадастровый номер единого недвижимого комплекса, в состав которого входит сооружение"""
    facility_cad_number: Optional[str] = None
    """Кадастровый номер предприятия как имущественного комплекса, в состав которого сооружение (имущественное право на здание) входит"""


class Options36384(OptionProperties):
    title_key = "cad_num"
    object_under_construction_record_record_type_value: Optional[str] = None
    """Вид объекта недвижимости"""
    registration_date: Optional[datetime] = None
    """Дата присвоения"""
    cad_num: Optional[str] = None
    """Кадастровый номер"""
    quarter_cad_number: Optional[str] = None
    """Кадастровый квартал"""
    readable_address: Optional[str] = None
    """Адрес"""
    object_under_construction_record_name: Optional[str] = None
    """Наименование"""
    height: Optional[float] = None
    """Высота (м.)"""
    depth: Optional[float] = None
    """Глубина (м.)"""
    occurence_depth: Optional[float] = None
    """Глубина залегания (м.)"""
    extension: Optional[float] = None
    """Протяжённость (м.)"""
    volume: Optional[float] = None
    """Объем (куб. м)"""
    built_up_area: Optional[float] = None
    """Площадь застройки (кв. м)"""
    common_data_status: Optional[str] = None
    """Статус"""
    ownership_type: Optional[str] = None
    """Форма собственности"""
    cost_value: Optional[float] = None
    """Кадастровая стоимость (руб.)"""
    cost_index: Optional[float] = None
    """Удельный показатель кадастровой стоимости (руб./ кв. м)"""
    degree_readiness: Optional[str] = None
    """Степень готовности ОНС в процентах (%)"""
    purpose: Optional[str] = None
    """Проектируемое значение основной характеристики"""
    facility_cad_number: Optional[str] = None
    """Кадастровый номер предприятия как имущественного комплекса, если объект незавершенного строительства (имущественное право на объект незавершенного строительства) входит в состав предприятия как имущественного комплекса"""


class Options36940(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options37158(OptionProperties):
    title_key = "nominal_number"
    nominal_number: Optional[str] = None
    """Условный номер образуемого земельного участка"""
    area: Optional[str] = None
    """Площадь образуемого земельного участка (кв. м)"""
    land_use_text: Optional[str] = None
    """Вид разрешенного использования образуемого земельного участка"""
    brd_nmb: Optional[str] = None
    """номер"""
    registration_date: Optional[datetime] = None
    """дата"""
    document_name: Optional[str] = None
    """документ"""
    document_number: Optional[str] = None
    """номер"""
    document_date: Optional[datetime] = None
    """дата"""
    document_issuer: Optional[str] = None
    """орган власти, организация выдавшие документ"""


class Options38030(OptionProperties):
    title_key = "name"
    obj_kind_value: Optional[str] = None
    """Тип"""
    name: Optional[str] = None
    """Наименование"""
    cad_num: Optional[str] = None
    """Учетный номер"""
    cnt_kr: Optional[float] = None
    """Количество кадастровых районов"""
    cnt_kk: Optional[float] = None
    """Количество кадастровых кварталов"""
    cnt_land: Optional[float] = None
    """Количество земельных участков"""
    cnt_land_geom: Optional[float] = None
    """c границами"""
    cnt_land_not_geom: Optional[float] = None
    """без границ"""
    cnt_oks: Optional[float] = None
    """Количество объектов капитального строительства"""
    cnt_oks_geom: Optional[float] = None
    """с границами"""
    cnt_oks_not_geom: Optional[float] = None
    """без границ"""
    cnt_enk: Optional[float] = None
    """Количество единых недвижимых комплексов"""
    cnt_pik: Optional[float] = None
    """Количество предприятий как имущественных комплексов"""


class Options38942(OptionProperties):
    title_key = "brd_nmb"
    content_restrict_encumbrances: Optional[str] = None
    """Ограничения"""
    doc: Optional[str] = None
    """Реквизиты решения об утверждении документации по планировке территории"""
    DOC_TYPE: Optional[str] = None
    """документ"""
    DOC_NUMBER: Optional[str] = None
    """номер"""
    DOC_DATE: Optional[datetime] = None
    """дата"""
    DOC_GOV: Optional[str] = None
    """орган власти, организация выдавшие документ"""


class Options38943(OptionProperties):
    title_key = "address"
    id: Optional[str] = None
    """ID"""
    doc_guid: Optional[str] = None
    """GUID"""
    doc_type: Optional[str] = None
    """Наименование вида документа об утверждении схемы расположения земельного участка"""
    doc_gov: Optional[str] = None
    """наименование уполномоченного органа"""
    doc_date: Optional[datetime] = None
    """дата"""
    doc_number: Optional[str] = None
    """номер"""
    cond_numbe: Optional[str] = None
    """Условный номер образуемого земельного участка"""
    shape_area: Optional[float] = None
    """Площадь (кв. м)"""
    address: Optional[str] = None
    """Адрес или иное описание местоположения земельного участка"""
    kvartal_id: Optional[str] = None
    """Кадастровый номер земельного участка, из которого в соответствии со схемой расположения земельного участка предусмотрено образование земельного участка"""
    name_zone: Optional[str] = None
    """Территориальная зона, в границах которой образуется земельный участок"""
    category_code: Optional[str] = None
    """Категория земель образуемого земельного"""
    utilization: Optional[str] = None
    """Вид разрешенного использования образуемого земельного участка"""


class Options38944(OptionProperties):
    schema1: Optional[str] = None
    """Тип"""
    name: Optional[str] = None
    """Наименование объекта"""
    part_type: Optional[str] = None
    """Тип части"""
    building: Optional[str] = None
    """Наличие объектов капитального строительства"""


class Options38967(OptionProperties):
    title_key = "process_ty_title"
    sub_rf: Optional[str] = None
    """Субъект РФ"""
    cad_distr: Optional[str] = None
    """Кадастровый округ"""
    district: Optional[str] = None
    """Район"""
    process_ty_title: Optional[str] = None
    """Вид и степень развития негативного процесса"""
    index_map: Optional[str] = None
    """Индекс"""
    shape_area: Optional[float] = None
    """Площадь проявления негативного процесса, га"""
    zone_proya: Optional[str] = None
    """Зона проявления"""
    process_ty: Optional[str] = None
    """Тип"""
    recommend: Optional[str] = None
    """Рекомендации по использованию земель"""
    year: Optional[str] = None
    """Год обследования"""


class Options38979(OptionProperties): ...


class Options38981(OptionProperties):
    title_key = "Кадастровый номер"
    auc_thrf: Optional[str] = None
    """Ссылка на аукцион"""


class Options38998(OptionProperties):
    title_key = "brd_nmb"
    type: Optional[str] = None
    """Вид"""
    brd_nmb: Optional[str] = None
    """Реестровый номер"""


class Options39228(OptionProperties):
    title_key = "terr_name"
    kkaccountnumber: Optional[str] = None
    """Учетный номер кадастрового квартала"""
    stateKKR: Optional[str] = None
    """Статус выполнения комплексных кадастровых работ"""
    contract: Optional[datetime] = None
    """Дата контракта на выполнение комплексных кадастровых работ"""
    contractNum: Optional[str] = None
    """Номер контракта на выполнение комплексных кадастровых работ"""
    krstartdate: Optional[datetime] = None
    """Дата начала комплексных кадастровых работ"""
    krenddate: Optional[datetime] = None
    """Дата окончания комплексных кадастровых работ"""
    krcustomername: Optional[str] = None
    """Наименование заказчика комплексных кадастровых работ"""
    krcustomeraddress: Optional[str] = None
    """Адрес заказчика комплексных кадастровых работ"""
    krcustomeremail: Optional[str] = None
    """Адрес электронной почты заказчика комплексных кадастровых работ"""
    krcustomerphone: Optional[str] = None
    """Телефон заказчика комплексных кадастровых работ"""
    krcontractorname: Optional[str] = None
    """Наименование юридического лица, с которым заключён контракт на выполнение комплексных кадастровых работ"""
    krsurveyorname: Optional[str] = None
    """ФИО кадастрового инженера"""
    krsurveyoraddress: Optional[str] = None
    """Адрес кадастрового инженера"""
    krsurveyoremail: Optional[str] = None
    """Адрес электронной почты кадастрового инженера"""
    krsurveyorphone: Optional[str] = None
    """Телефон кадастрового инженера"""
    krsurveyoratt: Optional[str] = None
    """Номер аттестата кадастрового инженера"""
    krsurveyorattdate: Optional[datetime] = None
    """Дата выдачи аттестата кадастрового инженера"""
    krsurveyorsroname: Optional[str] = None
    """Наименование саморегулируемой организации, членом которой является кадастровый инженер"""
    typeKKR: Optional[str] = None
    """Время выполнения работ/Место проведения работ/Виды работ"""
    krsurveyoraddress: Optional[str] = None
    """Адрес для предоставления документов о ранее учтенных земельных участках"""


class Options39663(OptionProperties):
    title_key = "cad_number"
    type: Optional[str] = None
    """Вид объекта недвижимости"""
    registration_date: Optional[str] = None
    """Дата присвоения"""
    cad_number: Optional[str] = None
    """Кадастровый номер"""
    quarter_cad_number: Optional[str] = None
    """Кадастровый квартал"""
    readable_address: Optional[str] = None
    """Адрес"""
    name: Optional[str] = None
    """Наименование"""
    purpose: Optional[str] = None
    """Назначение"""
    common_data_status: Optional[str] = None
    """Статус"""
    cost_value: Optional[float] = None
    """Кадастровая стоимость (руб.)"""
    facility_cad_number: Optional[str] = None
    """Кадастровый номер предприятия как имущественного комплекса, если единый недвижимый комплекс (имущественное право на него) входит в состав предприятия как имущественного комплекса"""


class Options39664(OptionProperties):
    title_key = "name"
    type: Optional[str] = None
    """Вид объекта недвижимости"""
    registration_date: Optional[str] = None
    """Дата присвоения"""
    name: Optional[str] = None
    """Наименование ПИК при наличии такого наименования"""
    purpose: Optional[str] = None
    """Назначение ПИК"""
    cad_number: Optional[str] = None
    """Кадастровый номер"""
    quarter_cad_number: Optional[str] = None
    """Кадастровый квартал"""
    readable_address: Optional[str] = None
    """Адрес"""
    common_data_status: Optional[str] = None
    """Статус"""
    cost_value: Optional[str] = None
    """Стоимость предприятия (руб.)"""


class Options472796(OptionProperties): ...


class Options472798(OptionProperties): ...


class Options472800(OptionProperties):
    title_key = "brd_nmb"
    brd_nmb: Optional[str] = None
    """Реестровый номер"""


class Options472805(OptionProperties):
    title_key = "brd_nmb"
    brd_nmb: Optional[str] = None
    """Реестровый номер"""


class Options472812(OptionProperties):
    title_key = "brd_nmb"
    brd_nmb: Optional[str] = None
    """Реестровый номер"""


class Options472813(OptionProperties):
    title_key = "brd_nmb"
    brd_nmb: Optional[str] = None
    """Реестровый номер границы"""


class Options472816(OptionProperties):
    title_key = "brd_nmb"
    brd_nmb: Optional[str] = None
    """Реестровый номер границы"""


class Options472819(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options472820(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options472825(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options472826(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options472827(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options472828(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options472846(OptionProperties):
    title_key = "brd_nmb"
    brd_nmb: Optional[str] = None
    """Реестровый номер границы"""


class Options472847(OptionProperties):
    title_key = "reg_numb_border"
    reg_numb_border: Optional[str] = None
    """Реестровый номер границы"""


class Options472853(OptionProperties): ...


class Options472860(OptionProperties): ...


class Layer36048Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36368]]
):
    """Земельные участки из ЕГРН"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Земельные участки из ЕГРН",
            "layerTreeId": 72,
            "layerId": 36048,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Росреестр: Земельные участки ЕГРН",
            "layerVisibleByDefault": False,
            "categoryId": 36368,
        }
    )


class Layer37236Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36368]]
):
    """Кадастровая стоимость объекта"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Кадастровая стоимость объекта",
            "layerTreeId": 69,
            "layerId": 37236,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Росреестр: Земельные участки ЕГРН. Кадастровая стоимость Тепловая карта",
            "layerVisibleByDefault": False,
            "categoryId": 36368,
        }
    )


class Layer37758Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36368]]
):
    """Удельный показатель кадастровой стоимости"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Удельный показатель кадастровой стоимости",
            "layerTreeId": 70,
            "layerId": 37758,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Росреестр: Земельные участки ЕГРН. Удельный Показатель Кадастровой Стоимости Тепловая карта",
            "layerVisibleByDefault": False,
            "categoryId": 36368,
        }
    )


class Layer36049Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36369]]
):
    """Здания"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Здания",
            "layerTreeId": 29,
            "layerId": 36049,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Росреестр: Здания ЕГРН",
            "layerVisibleByDefault": False,
            "categoryId": 36369,
        }
    )


class Layer36071Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36381]]
):
    """Кадастровые кварталы"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Кадастровые кварталы",
            "layerTreeId": 5,
            "layerId": 36071,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЕГРН. Кадастровые кварталы",
            "layerVisibleByDefault": False,
            "categoryId": 36381,
        }
    )


class Layer36070Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36382]]
):
    """Кадастровые районы"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Кадастровые районы ",
            "layerTreeId": 5873,
            "layerId": 36070,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЕГРН. Кадастровые районы",
            "layerVisibleByDefault": False,
            "categoryId": 36382,
        }
    )


class Layer36328Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36383]]
):
    """Сооружения"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Сооружения",
            "layerTreeId": 30,
            "layerId": 36328,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Росреестр: Сооружения ЕГРН",
            "layerVisibleByDefault": False,
            "categoryId": 36383,
        }
    )


class Layer36329Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36384]]
):
    """Объекты незавершенного строительства"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Объекты незавершенного строительства",
            "layerTreeId": 31,
            "layerId": 36329,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Росреестр: Объекты незавершённого строительства ЕГРН",
            "layerVisibleByDefault": False,
            "categoryId": 36384,
        }
    )


class Layer37577Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36940]]
):
    """ЗОУИТ объектов культурного наследия"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "ЗОУИТ объектов культурного наследия",
            "layerTreeId": 39,
            "layerId": 37577,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЗОУИТ объектов культурного наследия",
            "layerVisibleByDefault": False,
            "categoryId": 36940,
        }
    )


class Layer37578Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36940]]
):
    """ЗОУИТ объектов энергетики, связи, транспорта"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "ЗОУИТ объектов энергетики, связи, транспорта",
            "layerTreeId": 40,
            "layerId": 37578,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЗОУИТ объектов энергетики, связи, транспорта",
            "layerVisibleByDefault": False,
            "categoryId": 36940,
        }
    )


class Layer37580Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36940]]
):
    """ЗОУИТ природных территорий"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "ЗОУИТ природных территорий",
            "layerTreeId": 41,
            "layerId": 37580,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЗОУИТ природных территорий",
            "layerVisibleByDefault": False,
            "categoryId": 36940,
        }
    )


class Layer37579Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36940]]
):
    """ЗОУИТ охраняемых объектов и безопасности"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "ЗОУИТ охраняемых объектов и безопасности",
            "layerTreeId": 42,
            "layerId": 37579,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЗОУИТ охраняемых объектов и безопасности",
            "layerVisibleByDefault": False,
            "categoryId": 36940,
        }
    )


class Layer37581Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options36940]]
):
    """Иные ЗОУИТ"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Иные ЗОУИТ",
            "layerTreeId": 43,
            "layerId": 37581,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Иные ЗОУИТ",
            "layerVisibleByDefault": False,
            "categoryId": 36940,
        }
    )


class Layer36473Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options37158]]
):
    """Земельные участки, образуемые по проекту межевания территории"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Земельные участки, образуемые по проекту межевания территории",
            "layerTreeId": 21,
            "layerId": 36473,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Земельные участки, образуемые по проекту межевания территории (полигональный)",
            "layerVisibleByDefault": False,
            "categoryId": 37158,
        }
    )


class Layer36945Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38030]]
):
    """Кадастровые округа"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Кадастровые округа",
            "layerTreeId": 3,
            "layerId": 36945,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЕГРН. Кадастровые округа",
            "layerVisibleByDefault": False,
            "categoryId": 38030,
        }
    )


class Layer879243Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38942]]
):
    """Красные линии"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Красные линии ",
            "layerTreeId": 46,
            "layerId": 879243,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Красные линии ПКК",
            "layerVisibleByDefault": False,
            "categoryId": 38942,
        }
    )


class Layer37294Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38943]]
):
    """Земельные участки, образуемые по схеме расположения земельного участка"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Земельные участки, образуемые по схеме расположения земельного участка",
            "layerTreeId": 22,
            "layerId": 37294,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Схемы расположения земельных участков",
            "layerVisibleByDefault": False,
            "categoryId": 38943,
        }
    )


class Layer37295Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38944]]
):
    """Территория проведения мероприятий по ликвидации накопленного вреда окружающей среде, образовавшегося в результате производства химической продукции в г. Усолье-Сибирское Иркутской области"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Территория проведения мероприятий по ликвидации накопленного вреда окружающей среде, образовавшегося в результате производства химической продукции в г. Усолье-Сибирское Иркутской области",
            "layerTreeId": 64,
            "layerId": 37295,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Территория проведения мероприятий по ликвидации накопленного вреда окружающей среде, образовавшегося в результате производства химической продукции в г. Усолье-Сибирское Иркутской области",
            "layerVisibleByDefault": False,
            "categoryId": 38944,
        }
    )


class Layer872153Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Водная эрозия"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Водная эрозия",
            "layerTreeId": 33357,
            "layerId": 872153,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Водная эрозия",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872155Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Линейная эрозия"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Линейная эрозия",
            "layerTreeId": 33358,
            "layerId": 872155,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Линейная эрозия",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872164Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Ветровая эрозия"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Ветровая эрозия",
            "layerTreeId": 33359,
            "layerId": 872164,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Ветровая эрозия",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872182Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Опустынивание"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Опустынивание",
            "layerTreeId": 33360,
            "layerId": 872182,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Опустынивание",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872183Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Переувлажнение"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Переувлажнение",
            "layerTreeId": 33361,
            "layerId": 872183,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Переувлажнение",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872202Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Подтопление"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Подтопление",
            "layerTreeId": 33362,
            "layerId": 872202,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Подтопление",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872203Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Заболачивание"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Заболачивание",
            "layerTreeId": 33363,
            "layerId": 872203,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Заболачивание",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872205Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Затопление"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Затопление",
            "layerTreeId": 33364,
            "layerId": 872205,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Затопление",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872206Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Захламление"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Захламление",
            "layerTreeId": 33365,
            "layerId": 872206,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Захламление",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872210Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Обвально-осыпные и оползневые процессы"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Обвально-осыпные и оползневые процессы",
            "layerTreeId": 33366,
            "layerId": 872210,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Обвально-осыпные и оползневые процессы",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872211Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Абразия"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Абразия",
            "layerTreeId": 33367,
            "layerId": 872211,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Абразия",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872212Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Иные нарушенные земли"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Иные нарушенные земли ",
            "layerTreeId": 33368,
            "layerId": 872212,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Иные нарушенные земли",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872213Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Нарушенные земли при наземном строительстве"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Нарушенные земли при наземном строительстве ",
            "layerTreeId": 33369,
            "layerId": 872213,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Нарушенные земли при наземном строительстве",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872216Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Нарушенные земли при гидротехническом строительстве"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Нарушенные земли при гидротехническом строительстве",
            "layerTreeId": 33370,
            "layerId": 872216,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Нарушенные земли при гидротехническом строительстве",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872217Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Нарушенные земли при недропользовании"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Нарушенные земли при недропользовании",
            "layerTreeId": 33371,
            "layerId": 872217,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Нарушенные земли при недропользовании",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872218Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Нарушенные земли при промышленном лесопользовании"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Нарушенные земли при промышленном лесопользовании",
            "layerTreeId": 33372,
            "layerId": 872218,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Нарушенные земли при промышленном лесопользовании",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872219Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Нарушенные земли при сельскохозяйственном освоении"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Нарушенные земли при сельскохозяйственном освоении",
            "layerTreeId": 33373,
            "layerId": 872219,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Нарушенные земли при сельскохозяйственном освоении",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872220Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Нарушенные земли при проведении геологоразведочных, испытательных, эксплуатационных и иных работ"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Нарушенные земли при проведении геологоразведочных, испытательных, эксплуатационных и иных работ",
            "layerTreeId": 33374,
            "layerId": 872220,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Нарушенные земли при проведении геологоразведочных, испытательных, эксплуатационных и иных работ",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872221Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Нарушенные земли при складировании и захоронении промышленных отходов, загрязнение земель"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Нарушенные земли при складировании и захоронении промышленных отходов, загрязнение земель",
            "layerTreeId": 33375,
            "layerId": 872221,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Нарушенные земли при складировании и захоронении промышленных отходов, загрязнение земель",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872222Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Гари"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Гари",
            "layerTreeId": 33376,
            "layerId": 872222,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Гари",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872224Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Негативный процесс отсутствует"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Негативный процесс отсутствует",
            "layerTreeId": 33377,
            "layerId": 872224,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Негативный процесс отсутствует",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer872262Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38967]]
):
    """Засоление"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Засоление",
            "layerTreeId": 33378,
            "layerId": 872262,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Засоление",
            "layerVisibleByDefault": False,
            "categoryId": 38967,
        }
    )


class Layer37298Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38979]]
):
    """Земельные участки, свободные от прав третьих лиц"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Земельные участки, свободные от прав третьих лиц",
            "layerTreeId": 24,
            "layerId": 37298,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Земельные участки свободные от прав третьих лиц",
            "layerVisibleByDefault": False,
            "categoryId": 38979,
        }
    )


class Layer37299Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options38981]]
):
    """Земельные участки, выставленные на аукцион"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Земельные участки, выставленные на аукцион ",
            "layerTreeId": 23,
            "layerId": 37299,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Земельные участки, выставленные на аукцион",
            "layerVisibleByDefault": False,
            "categoryId": 38981,
        }
    )


class Layer37313Feature(
    BaseFeature[Union[MultiLineString, LineString], NspdProperties[Options38998]]
):
    """Государственная граница Российской Федерации"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Государственная граница Российской Федерации",
            "layerTreeId": 7,
            "layerId": 37313,
            "layerType": "wms",
            "geometryType": "LINESTRING",
            "layerName": "Государственная граница Российской Федерации",
            "layerVisibleByDefault": False,
            "categoryId": 38998,
        }
    )


class Layer37430Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options39228]]
):
    """Территории выполнения комплексных кадастровых работ"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Территории выполнения комплексных кадастровых работ",
            "layerTreeId": 66,
            "layerId": 37430,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "ЕГРН.Территории выполнения комплексных кадастровых работ",
            "layerVisibleByDefault": False,
            "categoryId": 39228,
        }
    )


class Layer37433Feature(
    BaseFeature[Union[MultiPoint, Point], NspdProperties[Options39663]]
):
    """Единые недвижимые комплексы"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Единые недвижимые комплексы",
            "layerTreeId": 35,
            "layerId": 37433,
            "layerType": "wms",
            "geometryType": "POINT",
            "layerName": "Единые недвижимые комплексы",
            "layerVisibleByDefault": False,
            "categoryId": 39663,
        }
    )


class Layer37434Feature(
    BaseFeature[Union[MultiPoint, Point], NspdProperties[Options39664]]
):
    """Предприятие как имущественный комплекс"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Предприятие как имущественный комплекс",
            "layerTreeId": 36,
            "layerId": 37434,
            "layerType": "wms",
            "geometryType": "POINT",
            "layerName": "Предприятие как имущественный комплекс",
            "layerVisibleByDefault": False,
            "categoryId": 39664,
        }
    )


class Layer875815Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472796]]
):
    """Субъекты Российской Федерации (линии)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Субъекты Российской Федерации (линии)",
            "layerTreeId": 42807,
            "layerId": 875815,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Субъекты Российской Федерации (линии)",
            "layerVisibleByDefault": False,
            "categoryId": 472796,
        }
    )


class Layer875817Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472798]]
):
    """Субъекты Российской Федерации (полигоны)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Субъекты Российской Федерации (полигоны)",
            "layerTreeId": 42808,
            "layerId": 875817,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Субъекты Российской Федерации (полигоны)",
            "layerVisibleByDefault": False,
            "categoryId": 472798,
        }
    )


class Layer875819Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472800]]
):
    """Муниципальные образования (полигональный)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Муниципальные образования (полигональный)",
            "layerTreeId": 42836,
            "layerId": 875819,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Муниципальные образования (полигональный)",
            "layerVisibleByDefault": False,
            "categoryId": 472800,
        }
    )


class Layer875824Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472805]]
):
    """Муниципальные образования (линейный)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Муниципальные образования (линейный)",
            "layerTreeId": 42837,
            "layerId": 875824,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Муниципальные образования (линейный)",
            "layerVisibleByDefault": False,
            "categoryId": 472805,
        }
    )


class Layer875831Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472812]]
):
    """Населённые пункты (полигоны)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Населённые пункты (полигоны)",
            "layerTreeId": 42857,
            "layerId": 875831,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Населённые пункты (полигоны)",
            "layerVisibleByDefault": False,
            "categoryId": 472812,
        }
    )


class Layer875832Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472813]]
):
    """Береговые линии (границы водных объектов) (полигональный)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Береговые линии (границы водных объектов) (полигональный)",
            "layerTreeId": 42864,
            "layerId": 875832,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Береговые линии (границы водных объектов) (полигональный)",
            "layerVisibleByDefault": False,
            "categoryId": 472813,
        }
    )


class Layer875835Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472816]]
):
    """Береговые линии (границы водных объектов)(линейный)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Береговые линии (границы водных объектов)(линейный)",
            "layerTreeId": 42865,
            "layerId": 875835,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Береговые линии (границы водных объектов) (линейный)",
            "layerVisibleByDefault": False,
            "categoryId": 472816,
        }
    )


class Layer875838Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472819]]
):
    """Территориальные зоны"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Территориальные зоны",
            "layerTreeId": 44234,
            "layerId": 875838,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Территориальные зоны",
            "layerVisibleByDefault": False,
            "categoryId": 472819,
        }
    )


class Layer875840Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472820]]
):
    """Территории объектов культурного наследия"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Территории объектов культурного наследия",
            "layerTreeId": 44235,
            "layerId": 875840,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Территории объекта культурного наследия",
            "layerVisibleByDefault": False,
            "categoryId": 472820,
        }
    )


class Layer875845Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472825]]
):
    """Особо охраняемые природные территории"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Особо охраняемые природные территории ",
            "layerTreeId": 44236,
            "layerId": 875845,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Особо охраняемые природные территории",
            "layerVisibleByDefault": False,
            "categoryId": 472825,
        }
    )


class Layer875846Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472826]]
):
    """Особые экономические зоны"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Особые экономические зоны",
            "layerTreeId": 44237,
            "layerId": 875846,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Особые экономические зоны",
            "layerVisibleByDefault": False,
            "categoryId": 472826,
        }
    )


class Layer875847Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472827]]
):
    """Охотничьи угодья"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Охотничьи угодья",
            "layerTreeId": 44238,
            "layerId": 875847,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Охотничьи угодья",
            "layerVisibleByDefault": False,
            "categoryId": 472827,
        }
    )


class Layer875848Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472828]]
):
    """Территории опережающего развития"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Территории опережающего развития",
            "layerTreeId": 44239,
            "layerId": 875848,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Территории опережающего развития",
            "layerVisibleByDefault": False,
            "categoryId": 472828,
        }
    )


class Layer875865Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472846]]
):
    """Игорные зоны"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Игорные зоны",
            "layerTreeId": 44240,
            "layerId": 875865,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Игорные зоны",
            "layerVisibleByDefault": False,
            "categoryId": 472846,
        }
    )


class Layer875866Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472847]]
):
    """Лесничества"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Лесничества",
            "layerTreeId": 44241,
            "layerId": 875866,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Лесничества",
            "layerVisibleByDefault": False,
            "categoryId": 472847,
        }
    )


class Layer875874Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472853]]
):
    """Граница лесопарка"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Граница лесопарка",
            "layerTreeId": 42872,
            "layerId": 875874,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Граница лесопарка",
            "layerVisibleByDefault": False,
            "categoryId": 472853,
        }
    )


class Layer875882Feature(
    BaseFeature[Union[MultiPolygon, Polygon, Point], NspdProperties[Options472860]]
):
    """Населённые пункты (линии)"""

    layer_meta = LayerNode.model_validate(
        {
            "title": "Населённые пункты (линии)",
            "layerTreeId": 42858,
            "layerId": 875882,
            "layerType": "wms",
            "geometryType": "POLYGON",
            "layerName": "Населённые пункты (линии)",
            "layerVisibleByDefault": False,
            "categoryId": 472860,
        }
    )
