name: schema-update

on:
  push:
    branches:
      - 3-*
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  check:
    if: github.repository_owner == 'yazmolod'
    runs-on: self-hosted
    steps:
      # https://github.com/actions/runner/issues/686#issuecomment-1636899369
      - name: powershell allow...
        shell: cmd
        run: pwsh -Command "Set-ExecutionPolicy Unrestricted -Scope CurrentUser"

      - uses: actions/checkout@v4
      
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run schema update script
        run:
          uv run ./scripts/autogeneration.py && 
          uv run ruff check --fix && 
          uv run ruff check --select I --fix && 
          ruff format

      - name: "Set current date as env variable"
        run: |
          echo "builddate=$((Get-Date).ToString('yyyy-MM-dd'))" >> $GITHUB_OUTPUT
        id: version

      - run: echo ${{ steps.version.outputs.builddate }}

      - uses: EndBug/add-and-commit@v9
        with:
          message: "${{ steps.version.outputs.builddate }} schema update"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com